name: ui_components
description: UI Components Jaspr libraries.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

workspace:
  - packages/deepyr

dependencies:
  jaspr: ^0.21.7

# Spezifiziere lint und test in den dev_dependencies damit diese sich alle Projekte teilen kÃ¶nnen.
dev_dependencies:
  build_runner: ^2.10.2
  build_web_compilers: ^4.4.1
  jaspr_builder: ^0.21.6
  test: ^1.26.3
  very_good_analysis: ^10.0.0
