name: ui_components
description: UI Components Jaspr libraries.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/deepyr

dependencies:
  jaspr: ^0.20.0

# Spezifiziere lint und test in den dev_dependencies damit diese sich alle Projekte teilen kÃ¶nnen.
dev_dependencies:
  jaspr_builder: ^0.20.0
  test: ^1.26.0
  very_good_analysis: ^9.0.0
