name: example
description: A new Jaspr project, Deepyr example
version: 0.1.4
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  jaspr: ^0.21.7
  deepyr: ^0.4.0

dev_dependencies:
  build_runner: ^2.10.2
  build_web_compilers: ^4.4.1
  jaspr_builder: ^0.21.1
  jaspr_lints: ^0.5.1
  lints: ^6.0.0

jaspr:
  mode: static
