name: deepyr
description: A type-safe Dart implementation of daisyUI components for Jaspr, providing a fluent API for building beautiful web apps (PoC)
version: 0.4.0
homepage: https://deepyr-doc.web.app/
repository: https://github.com/PhilippHGerber/ui_components
issue_tracker: https://github.com/PhilippHGerber/ui_components/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  jaspr: ^0.22.0
  universal_web: ^1.1.0

dev_dependencies:
  build_runner: ^2.10.2
  build_web_compilers: ^4.4.1
  jaspr_builder: ^0.22.0
  jaspr_lints: ^0.6.0
  #  jaspr_web_compilers: ^4.1.1
  jaspr_test: ^0.22.0
  test: ^1.26.0
  very_good_analysis: ^10.0.0

topics:
  - jaspr
  - daisyui
  - ui-components
  - web

screenshots:
  - description: "Deepyr Logo"
    path: pub/logo.png
  - description: "Deepyr Component Example"
    path: pub/components_light.png
  - description: "Deepyr Component Example (Dark Mode)"
    path: pub/components_dark.png
